name: internationalization
description: A project to easily implement internationalization on flutter projects
version: 4.1.0
homepage: https://github.com/TercyoStorck/internationalization

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: