name: internationalization
description: A project to easily implement internationalization on flutter projects
version: 4.0.0+1
homepage: https://github.com/TercyoStorck/internationalization

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0